import type { MissionBodyPart } from "@/utils/dailyMission"

export type ExerciseDifficulty = "初心者" | "中級" | "上級"
export type ExerciseEquipment = "バーベル" | "ダンベル" | "マシン" | "自重"
export type ProfileGender = "male" | "female" | "unspecified"

export interface ExerciseGuideEntry {
  name: string
  bodyPart: MissionBodyPart
  difficulty: ExerciseDifficulty
  equipment: ExerciseEquipment
  targetMuscles: {
    primary: string[]
    secondary: string[]
  }
  description: string
  formTips: string[]
  commonMistakes: string[]
  suggestedSets: string
  suggestedReps: string
  beginnerWeightMale: number
  beginnerWeightFemale: number
}

const EXERCISE_DATABASE: ExerciseGuideEntry[] = [
  {
    name: "ベンチプレス",
    bodyPart: "chest",
    difficulty: "初心者",
    equipment: "バーベル",
    targetMuscles: { primary: ["大胸筋"], secondary: ["三角筋前部", "上腕三頭筋"] },
    description: "胸全体を鍛える王道種目です。フォームを安定させると安全に高重量へ進めます。",
    formTips: ["肩甲骨を寄せて胸を張る", "足裏で床を押して体幹を安定させる", "バーはみぞおち寄りに下ろす", "手首を寝かせすぎない"],
    commonMistakes: ["肘を開きすぎる", "お尻がベンチから浮く", "反動でバーを跳ね返す"],
    suggestedSets: "3〜4セット",
    suggestedReps: "8〜12回",
    beginnerWeightMale: 20,
    beginnerWeightFemale: 10,
  },
  {
    name: "ダンベルフライ",
    bodyPart: "chest",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["大胸筋"], secondary: ["三角筋前部"] },
    description: "胸を大きくストレッチさせながら刺激できる種目です。可動域を丁寧に使うのがポイントです。",
    formTips: ["肘を軽く曲げたまま固定する", "胸を開く意識で下ろす", "肩がすくまないようにする", "ダンベルは胸の上で合わせる"],
    commonMistakes: ["肘の角度が毎回変わる", "下ろしすぎて肩を痛める", "勢いで持ち上げる"],
    suggestedSets: "3セット",
    suggestedReps: "10〜15回",
    beginnerWeightMale: 8,
    beginnerWeightFemale: 4,
  },
  {
    name: "チェストプレス",
    bodyPart: "chest",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["大胸筋"], secondary: ["上腕三頭筋", "三角筋前部"] },
    description: "軌道が安定していて初心者でも扱いやすい胸トレマシンです。ベンチプレス前の練習にも向いています。",
    formTips: ["シートを握り位置が胸の高さになるよう調整する", "肩を下げて胸を張る", "押し切っても肘を伸ばし切らない", "戻す時もゆっくりコントロールする"],
    commonMistakes: ["シート位置が高すぎる", "肩が前に出る", "戻しを速くしすぎる"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 25,
    beginnerWeightFemale: 15,
  },
  {
    name: "インクラインダンベルプレス",
    bodyPart: "chest",
    difficulty: "中級",
    equipment: "ダンベル",
    targetMuscles: { primary: ["大胸筋上部"], secondary: ["三角筋前部", "上腕三頭筋"] },
    description: "胸上部を狙いやすいプレス種目です。ベンチ角度を上げすぎないと胸に入りやすくなります。",
    formTips: ["ベンチ角度は30〜45度にする", "肩甲骨を寄せて固定する", "ダンベルは胸の外側へ下ろす", "押す時に肘を内側へ寄せる"],
    commonMistakes: ["ベンチ角度が立ちすぎる", "肩で押してしまう", "ダンベル同士をぶつける"],
    suggestedSets: "3セット",
    suggestedReps: "8〜12回",
    beginnerWeightMale: 10,
    beginnerWeightFemale: 5,
  },
  {
    name: "プッシュアップ",
    bodyPart: "chest",
    difficulty: "初心者",
    equipment: "自重",
    targetMuscles: { primary: ["大胸筋"], secondary: ["上腕三頭筋", "体幹"] },
    description: "自宅でもできる基本種目です。体幹を固めることで胸にしっかり効かせられます。",
    formTips: ["頭からかかとまで一直線を保つ", "手は肩幅より少し広めに置く", "胸を床へ近づける", "お腹に力を入れて腰を反らさない"],
    commonMistakes: ["腰が落ちる", "首だけ前に出る", "浅い可動域で終わる"],
    suggestedSets: "3セット",
    suggestedReps: "8〜15回",
    beginnerWeightMale: 0,
    beginnerWeightFemale: 0,
  },
  {
    name: "ラットプルダウン",
    bodyPart: "back",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["広背筋"], secondary: ["大円筋", "上腕二頭筋"] },
    description: "背中の広がりを作る代表種目です。引く前に肩を下げる意識が大切です。",
    formTips: ["胸を張ってバーを鎖骨付近へ引く", "肩をすくめず肩甲骨を下げる", "反動を使わず背中で引く", "戻す時に広背筋を伸ばす"],
    commonMistakes: ["体を大きく後ろへ倒す", "腕だけで引く", "バーを首の後ろへ引く"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 25,
    beginnerWeightFemale: 15,
  },
  {
    name: "シーテッドロウ",
    bodyPart: "back",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["広背筋", "僧帽筋中部"], secondary: ["上腕二頭筋", "後部三角筋"] },
    description: "背中の厚みを作る基本種目です。引き切る位置を毎回そろえると効きやすくなります。",
    formTips: ["胸を張って骨盤を立てる", "肘を後ろへ引く意識を持つ", "肩甲骨を最後に寄せる", "戻す時に背中を丸めない"],
    commonMistakes: ["腰を反りすぎる", "肩が前に出る", "勢いで引く"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 25,
    beginnerWeightFemale: 15,
  },
  {
    name: "デッドリフト",
    bodyPart: "back",
    difficulty: "上級",
    equipment: "バーベル",
    targetMuscles: { primary: ["脊柱起立筋", "大臀筋", "ハムストリングス"], secondary: ["広背筋", "前腕"] },
    description: "全身を使う高重量種目です。フォーム習得までは軽めで丁寧に練習するのが安全です。",
    formTips: ["バーを足の近くに保つ", "背中を丸めず胸を張る", "床を押して立ち上がる", "トップで反りすぎない"],
    commonMistakes: ["背中が丸まる", "バーが体から離れる", "腕で引こうとする"],
    suggestedSets: "3セット",
    suggestedReps: "5〜8回",
    beginnerWeightMale: 30,
    beginnerWeightFemale: 20,
  },
  {
    name: "ワンハンドダンベルロウ",
    bodyPart: "back",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["広背筋"], secondary: ["僧帽筋", "上腕二頭筋"] },
    description: "左右差を整えやすい背中種目です。肘を腰へ引く軌道を意識すると広背筋に入りやすいです。",
    formTips: ["背中を床と平行に近づける", "肘を腰へ向けて引く", "肩をすくめない", "下ろす時に背中を伸ばす"],
    commonMistakes: ["体をひねって反動を使う", "ダンベルを真上に引く", "首に力が入る"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 10,
    beginnerWeightFemale: 6,
  },
  {
    name: "バックエクステンション",
    bodyPart: "back",
    difficulty: "初心者",
    equipment: "自重",
    targetMuscles: { primary: ["脊柱起立筋"], secondary: ["大臀筋", "ハムストリングス"] },
    description: "腰背部を安全に鍛えやすい種目です。反りすぎず一直線まで起こすのが基本です。",
    formTips: ["骨盤をパッドにしっかり当てる", "背中を丸めすぎず伸ばしすぎない", "お尻を締めながら起こす", "トップで止まりすぎない"],
    commonMistakes: ["上体を反らしすぎる", "勢いで上下する", "首を上げすぎる"],
    suggestedSets: "2〜3セット",
    suggestedReps: "12〜15回",
    beginnerWeightMale: 0,
    beginnerWeightFemale: 0,
  },
  {
    name: "スクワット",
    bodyPart: "legs",
    difficulty: "初心者",
    equipment: "バーベル",
    targetMuscles: { primary: ["大腿四頭筋", "大臀筋"], secondary: ["ハムストリングス", "体幹"] },
    description: "脚とお尻を中心に全身を鍛える基本種目です。まずは深さと安定感を優先しましょう。",
    formTips: ["足裏全体で床を踏む", "膝とつま先の向きをそろえる", "胸を張ってしゃがむ", "立ち上がる時に膝が内側へ入らないようにする"],
    commonMistakes: ["かかとが浮く", "膝が内側に入る", "腰が丸まる"],
    suggestedSets: "3〜4セット",
    suggestedReps: "8〜12回",
    beginnerWeightMale: 20,
    beginnerWeightFemale: 10,
  },
  {
    name: "レッグプレス",
    bodyPart: "legs",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["大腿四頭筋", "大臀筋"], secondary: ["ハムストリングス"] },
    description: "スクワットより安定して脚を追い込みやすいマシンです。深く下ろしすぎず腰を守りましょう。",
    formTips: ["腰をシートに密着させる", "膝を伸ばし切らない", "足幅は肩幅程度にする", "下ろす時に膝をコントロールする"],
    commonMistakes: ["膝をロックする", "腰が丸まるほど深く下ろす", "つま先だけで押す"],
    suggestedSets: "3セット",
    suggestedReps: "10〜15回",
    beginnerWeightMale: 60,
    beginnerWeightFemale: 40,
  },
  {
    name: "レッグカール",
    bodyPart: "legs",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["ハムストリングス"], secondary: ["腓腹筋"] },
    description: "もも裏を集中的に鍛える種目です。反動を使わず収縮を感じることが大切です。",
    formTips: ["膝の位置をマシンの軸に合わせる", "骨盤を浮かせない", "曲げ切った位置で一瞬止める", "戻しをゆっくり行う"],
    commonMistakes: ["腰が反る", "勢いで巻き上げる", "可動域が浅い"],
    suggestedSets: "3セット",
    suggestedReps: "10〜15回",
    beginnerWeightMale: 20,
    beginnerWeightFemale: 12,
  },
  {
    name: "ブルガリアンスクワット",
    bodyPart: "legs",
    difficulty: "中級",
    equipment: "ダンベル",
    targetMuscles: { primary: ["大臀筋", "大腿四頭筋"], secondary: ["ハムストリングス", "体幹"] },
    description: "片脚ずつ鍛えられるためバランス改善に役立ちます。最初は自重でも十分きつい種目です。",
    formTips: ["前足に体重を乗せる", "上体を少し前傾させる", "膝が内側に入らないようにする", "後ろ足は補助程度に使う"],
    commonMistakes: ["歩幅が狭すぎる", "前足のかかとが浮く", "上体がぶれすぎる"],
    suggestedSets: "2〜3セット",
    suggestedReps: "左右10回ずつ",
    beginnerWeightMale: 6,
    beginnerWeightFemale: 4,
  },
  {
    name: "カーフレイズ",
    bodyPart: "legs",
    difficulty: "初心者",
    equipment: "自重",
    targetMuscles: { primary: ["腓腹筋", "ヒラメ筋"], secondary: [] },
    description: "ふくらはぎを鍛えるシンプルな種目です。トップでしっかりかかとを上げ切りましょう。",
    formTips: ["つま先で真上に押し上げる", "トップで1秒止める", "下ろす時にかかとをしっかり下げる", "反動を使わない"],
    commonMistakes: ["可動域が狭い", "勢いで上下する", "つま先の向きが毎回変わる"],
    suggestedSets: "3セット",
    suggestedReps: "15〜20回",
    beginnerWeightMale: 0,
    beginnerWeightFemale: 0,
  },
  {
    name: "ショルダープレス",
    bodyPart: "shoulders",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["三角筋前部", "三角筋中部"], secondary: ["上腕三頭筋"] },
    description: "肩全体を鍛える基本プレスです。腰を反りすぎず真上へ押す軌道を意識しましょう。",
    formTips: ["お腹に力を入れて腰を守る", "肘を手首の真下に置く", "耳の横へ押し上げる", "下ろす位置をあご〜耳の高さにそろえる"],
    commonMistakes: ["腰を反りすぎる", "ダンベルが前に流れる", "肩をすくめる"],
    suggestedSets: "3セット",
    suggestedReps: "8〜12回",
    beginnerWeightMale: 8,
    beginnerWeightFemale: 4,
  },
  {
    name: "サイドレイズ",
    bodyPart: "shoulders",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["三角筋中部"], secondary: ["僧帽筋上部"] },
    description: "肩幅を作る定番種目です。軽めの重量で丁寧に行うほど効きやすいです。",
    formTips: ["肘を軽く曲げて固定する", "小指側を少し上げる意識で持ち上げる", "肩の高さまで上げる", "反動を最小限にする"],
    commonMistakes: ["重すぎて反動を使う", "肩をすくめる", "腕を上げすぎる"],
    suggestedSets: "3セット",
    suggestedReps: "12〜15回",
    beginnerWeightMale: 4,
    beginnerWeightFemale: 2,
  },
  {
    name: "フロントレイズ",
    bodyPart: "shoulders",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["三角筋前部"], secondary: ["上部胸筋"] },
    description: "肩前部を狙う補助種目です。勢いを使わず前へ持ち上げることが重要です。",
    formTips: ["肘を軽く曲げる", "肩の高さまで上げる", "体を反らさない", "下ろす時もゆっくり行う"],
    commonMistakes: ["上げすぎる", "腰を反って反動を使う", "首に力が入る"],
    suggestedSets: "2〜3セット",
    suggestedReps: "10〜15回",
    beginnerWeightMale: 4,
    beginnerWeightFemale: 2,
  },
  {
    name: "リアデルトフライ",
    bodyPart: "shoulders",
    difficulty: "中級",
    equipment: "ダンベル",
    targetMuscles: { primary: ["三角筋後部"], secondary: ["僧帽筋中部", "菱形筋"] },
    description: "猫背改善にも役立つ肩後部種目です。軽い重量で後ろへ広げる感覚をつかみましょう。",
    formTips: ["上体を前傾させる", "肩甲骨を寄せすぎず肩後部で開く", "肘を横へ広げる", "首をすくめない"],
    commonMistakes: ["背中で引きすぎる", "反動を使う", "上体が起き上がる"],
    suggestedSets: "3セット",
    suggestedReps: "12〜15回",
    beginnerWeightMale: 4,
    beginnerWeightFemale: 2,
  },
  {
    name: "アームカール",
    bodyPart: "arms",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["上腕二頭筋"], secondary: ["腕橈骨筋"] },
    description: "腕前面を鍛える基本種目です。肘の位置を固定すると二頭筋に集中できます。",
    formTips: ["肘を体の横で固定する", "手首を反らしすぎない", "上げ切った位置で軽く止める", "下ろす時に力を抜かない"],
    commonMistakes: ["体を反らして反動を使う", "肘が前に出る", "下ろしを速くする"],
    suggestedSets: "3セット",
    suggestedReps: "10〜15回",
    beginnerWeightMale: 6,
    beginnerWeightFemale: 3,
  },
  {
    name: "トライセプスエクステンション",
    bodyPart: "arms",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["上腕三頭筋"], secondary: [] },
    description: "二の腕を集中的に鍛える種目です。肘を閉じて動かすと三頭筋に入りやすくなります。",
    formTips: ["肘をできるだけ閉じる", "上腕を固定する", "頭の後ろへゆっくり下ろす", "押し上げる時に肘を伸ばし切る手前で止める"],
    commonMistakes: ["肘が開く", "腰を反る", "可動域が浅い"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 8,
    beginnerWeightFemale: 4,
  },
  {
    name: "ハンマーカール",
    bodyPart: "arms",
    difficulty: "初心者",
    equipment: "ダンベル",
    targetMuscles: { primary: ["腕橈骨筋", "上腕二頭筋"] , secondary: ["前腕"] },
    description: "前腕も一緒に鍛えやすいカール種目です。握力強化にもつながります。",
    formTips: ["手のひらを向かい合わせに保つ", "肘を固定する", "肩をすくめない", "下ろす時にゆっくり耐える"],
    commonMistakes: ["ダンベルを振り上げる", "肘が前に出る", "手首が折れる"],
    suggestedSets: "3セット",
    suggestedReps: "10〜12回",
    beginnerWeightMale: 6,
    beginnerWeightFemale: 3,
  },
  {
    name: "ケーブルプレスダウン",
    bodyPart: "arms",
    difficulty: "初心者",
    equipment: "マシン",
    targetMuscles: { primary: ["上腕三頭筋"], secondary: [] },
    description: "三頭筋を安全に追い込みやすいケーブル種目です。肘を固定して押し切りましょう。",
    formTips: ["肘を脇腹の横で固定する", "肩を下げて胸を張る", "手首を返しすぎない", "戻す時にゆっくり耐える"],
    commonMistakes: ["上体を大きく前後させる", "肘が開く", "肩で押してしまう"],
    suggestedSets: "3セット",
    suggestedReps: "12〜15回",
    beginnerWeightMale: 20,
    beginnerWeightFemale: 10,
  },
  {
    name: "ディップス",
    bodyPart: "arms",
    difficulty: "上級",
    equipment: "自重",
    targetMuscles: { primary: ["上腕三頭筋", "大胸筋下部"], secondary: ["三角筋前部"] },
    description: "自重で高負荷をかけられる押す種目です。肩に不安がある場合は無理せず補助付きで行いましょう。",
    formTips: ["肩をすくめず胸を張る", "肘を後ろへ曲げる", "深く下ろしすぎない", "反動を使わず押し上げる"],
    commonMistakes: ["肩が前に出る", "勢いで上下する", "可動域を深くしすぎる"],
    suggestedSets: "2〜3セット",
    suggestedReps: "6〜10回",
    beginnerWeightMale: 0,
    beginnerWeightFemale: 0,
  },
]

export const exerciseDatabase = EXERCISE_DATABASE

export const exerciseBodyPartLabels: Record<MissionBodyPart, string> = {
  chest: "胸",
  back: "背中",
  legs: "脚",
  shoulders: "肩",
  arms: "腕",
}

export function normalizeExerciseName(value: string) {
  return value.trim().toLowerCase().replace(/\s+/g, "")
}

export function getExerciseGuideEntry(exerciseName: string) {
  const normalized = normalizeExerciseName(exerciseName)
  return exerciseDatabase.find((exercise) => normalizeExerciseName(exercise.name) === normalized) ?? null
}

export function getBeginnerWeightLabel(exerciseName: string, gender: ProfileGender = "male") {
  const exercise = getExerciseGuideEntry(exerciseName)
  if (!exercise) return null
  const resolvedGender = gender === "female" ? "female" : "male"
  const weight = resolvedGender === "female" ? exercise.beginnerWeightFemale : exercise.beginnerWeightMale
  return weight > 0 ? `${weight}kg目安` : "まずは自重でフォーム習得"
}

export function getExerciseHint(exerciseName: string) {
  return getExerciseGuideEntry(exerciseName)?.formTips[0] ?? null
}